### ISSUE TITLE
Provide documentation for obtaining mSigDB data

### ISSUE THREAD

**Issue by sorrywm** [nclark-lab/RERconverge#12]
Write up instructions for downloading the dataset.
Write a function to read in the files.

**Comment by wgmao** [comment]
1. Instruction is listed as follows,

In order to download mSigDB data, you have to be a registered user. If you haven't registered, please go to the registration page (http://software.broadinstitute.org/gsea/register.jsp). After your registration is approved, login with your email address. Then go to "Download"(http://software.broadinstitute.org/gsea/downloads.jsp) page, and you can find links to download different categories of gene set collections (.gmt files) in the bottom part of the page. For details of the gene set collections, please refer to the "Molecular Signature Database" (http://software.broadinstitute.org/gsea/msigdb/index.jsp) page and pick up the gene set you want to download.


2.
read.gmt() function, which takes .gmt file as input, is recorded in https://github.com/nclark-lab/RERconverge/blob/master/R/enrichmentFuncs.R, adopted from GSA package.
