### ISSUE TITLE
Gene tree input other than PAML

### ISSUE THREAD

**Issue by evolgen** [nclark-lab/RERconverge#54]
Hi developers,

Thanks for the wonderful tool.
I had a naive query regarding the gene trees. I tried to use ML trees for each gene, but their topology varies. In your paper, you suggest using PAML to build the trees. However, I was wondering if we could use dS trees which represent neutrality or dN trees, generated with Hyphy? Or are there other alternatives apart from PAML trees you would suggest?

Thank you for your time.

**Comment by nclark-lab** [comment]
Hello,

We think that dN trees would be useful since they would reflect amino acid distances. As long as the trees have the same topology and they reflect the type of divergence you want to study, then the method will work.
Another alternative we are working up is to use an R package called phangorn. A student in the lab is working on putting the functions and a vignette for that on the main branch right now.

Best,
-Nathan


On Jun 17, 2020, at 11:12 AM, evolgen <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi developers,

Thanks for the wonderful tool.
I had a naive query regarding the gene trees. I tried to use ML trees for each gene, but their topology varies. In your paper, you suggest using PAML to build the trees. However, I was wondering if we could use dS trees which represent neutrality or dN trees, generated with Hyphy? Or are there other alternatives apart from PAML trees you would suggest?

Thank you for your time.

**Comment by evolgen** [comment]
Thanks Nathan, that clears things up. The phangorn update for generating trees sounds really cool. Looking forward to it.

Cheers,
Rohit

**Comment by nclark-lab** [comment]
Amanda, Rohit is looking for a way to make trees as an alternative to PAML. Could you point out the relevant files on GitHub?
thanks!
-Nathan


On Jun 25, 2020, at 6:31 PM, evolgen <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks Nathan, that clears things up. The phangorn update for generating trees sounds really cool. Looking forward to it.

Cheers,
Rohit

**Comment by Amylith** [comment]
Hi Rohit,

I literally just merged these functions into the master branch today!  If you reinstall RERconverge, they should be included.  They are called estimatePhangornTree and estimatePhangornTreeAll and you can find them in the estimateTreeFuncs.R script.  All of the parameters have defaults, so you can run them with just a tree topology and alignments, but you can also change those parameters, which are passed on to the phangorn functions.  Let me know if you have any problems with them!

Best,
Amanda

**Comment by evolgen** [comment]
Many thanks Amanda. I will try this new merge asap.
That's really nice of you both you and Nathan for automating the whole workflow. 

Best,
Rohit
