### ISSUE TITLE
Discordant gene trees

### ISSUE THREAD

**Issue by navyashukla-uom** [nclark-lab/RERconverge#86]
Hello, 
I've getting the following error when I try to calculate my residuals:

Discordant tree topology detected - gene/trait tree and treesObj$masterTree have irreconcilable topologies

However, I'm not sure why (please forgive me if I'm misunderstanding something):
1. The genes trees all have the same topology (constrained to have this) 

2. All species are present in all gene trees. 

Given that the master tree is being estimated from the gene trees, I don't understand how it can be discordant? 
[rer_input.txt](https://github.com/nclark-lab/RERconverge/files/14150576/rer_input.txt)

**Comment by charlesfeigin** [comment]
I'm having a similar issue with the most recent version and nearly all of my residuals are being set to NA despite being, by all measures I can see, concordant (I fixed everything to the same topology). The NA issue seems to track back to Commit 64089d7, but I can't figure out how to resolve this since my trees all have the same topology (btw, hi Navya!)

**Comment by navyashukla-uom** [comment]
Hey Charlie!! I just had a look at the input file I've attached above to see if I can remember, the error seemed to be happending because of one annotation (chr21_13815758-13815809) which had estimated branch lengths 0 for a couple of species. Removing that row was fixing the irreconcilable topologies error at least

**Comment by nclark-lab** [comment]
With the rer_input.txt trees above, and the current RERconverge version, I didn't get an error about discordant topologies.
